/*
 * Copyright (c) 2020 Dario Kondratiuk
 * Modifications copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System;

namespace PlaywrightNative.Helpers
{
    /// <summary>
    /// Shared rules for page-level <c>request</c> events. Mirrors official Playwright:
    /// lowercase resource types, hide favicon / preflight OPTIONS, keep the last 100
    /// requests for <c>page.requests()</c>.
    /// </summary>
    internal static class NetworkRequestEvents
    {
        /// <summary>
        /// Official Playwright retains only the last 100 page-level requests.
        /// </summary>
        internal const int RecentRequestLimit = 100;

        /// <summary>
        /// Returns <see langword="true"/> when the protocol resource type is a document
        /// navigation (CDP <c>Document</c>, WebKit <c>Document</c>/<c>document</c>).
        /// </summary>
        /// <param name="resourceType">The protocol resource type.</param>
        /// <returns><see langword="true"/> for document navigations.</returns>
        internal static bool IsDocumentNavigation(string resourceType)
        {
            return !string.IsNullOrEmpty(resourceType)
                && string.Equals(resourceType, "Document", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Maps a protocol resource type (e.g. <c>XHR</c>, <c>Document</c>) to the
        /// official Playwright value (<c>xhr</c>, <c>document</c>).
        /// </summary>
        /// <param name="resourceType">The protocol resource type.</param>
        /// <returns>The lower-cased type, or empty when <paramref name="resourceType"/> is null.</returns>
        internal static string NormalizeResourceType(string resourceType)
        {
            if (string.IsNullOrEmpty(resourceType))
            {
                return resourceType ?? string.Empty;
            }

#pragma warning disable CA1308 // Official Playwright resource types are lowercase ASCII.
            return resourceType.ToLowerInvariant();
#pragma warning restore CA1308
        }

        /// <summary>
        /// Official WebKit skips <c>data:</c> and <c>about:</c> after
        /// <c>commits.webkit.org/292206@main</c> started dispatching them.
        /// </summary>
        /// <param name="url">The request URL.</param>
        /// <returns><see langword="true"/> for internal documents.</returns>
        internal static bool IsInternalDocumentUrl(string url)
        {
            return !string.IsNullOrEmpty(url)
                && (url.StartsWith("data:", StringComparison.OrdinalIgnoreCase)
                    || url.StartsWith("about:", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Favicon housekeeping requests are not exposed or routed.
        /// </summary>
        /// <param name="url">The request URL.</param>
        /// <returns><see langword="true"/> for favicon URLs.</returns>
        internal static bool IsFaviconUrl(string url)
        {
            return !string.IsNullOrEmpty(url)
                && url.Contains("/favicon.ico", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Returns <see langword="true"/> when the request is a CORS preflight
        /// generated by the network stack. A page-initiated
        /// <c>fetch(url, { method: 'OPTIONS' })</c> is not a preflight.
        /// </summary>
        /// <param name="method">The HTTP method.</param>
        /// <param name="resourceType">The protocol resource type.</param>
        /// <returns><see langword="true"/> for resource type <c>preflight</c>.</returns>
        internal static bool IsPreflight(string method, string resourceType)
        {
            return !string.IsNullOrEmpty(resourceType)
                && string.Equals(resourceType, "preflight", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Returns <see langword="true"/> when the request must not be exposed on
        /// <see cref="IPage.Request"/> (favicon housekeeping or CORS preflight OPTIONS).
        /// </summary>
        /// <param name="url">The request URL.</param>
        /// <param name="method">The HTTP method.</param>
        /// <param name="resourceType">The protocol resource type (any casing).</param>
        /// <returns><see langword="true"/> when page listeners must not see the request.</returns>
        internal static bool IsHiddenFromPage(string url, string method, string resourceType)
        {
            if (IsFaviconUrl(url) || NetworkIdleRules.IsIgnoredUrl(url) || IsInternalDocumentUrl(url))
            {
                return true;
            }

            return IsPreflight(method, resourceType);
        }
    }
}
