// Copyright (c) Microsoft Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
#pragma warning disable SA1211

// Global aliases so existing PlaywrightSharp code resolves official Microsoft.Playwright
// contract types (binary-compatible with playwright-dotnet).
// Do not `global using Microsoft.Playwright` — it collides with PlaywrightSharp.Playwright.
global using AnnotatePosition = Microsoft.Playwright.AnnotatePosition;
global using AriaRole = Microsoft.Playwright.AriaRole;
global using AriaSnapshotMode = Microsoft.Playwright.AriaSnapshotMode;
global using BindingSource = Microsoft.Playwright.BindingSource;
global using BrowserContextCookiesResult = Microsoft.Playwright.BrowserContextCookiesResult;
global using ClientCertificate = Microsoft.Playwright.ClientCertificate;
global using Clip = Microsoft.Playwright.Clip;
global using ClockInstallOptions = Microsoft.Playwright.ClockInstallOptions;
global using ColorScheme = Microsoft.Playwright.ColorScheme;
global using ConsoleMessagesFilter = Microsoft.Playwright.ConsoleMessagesFilter;
global using Contrast = Microsoft.Playwright.Contrast;
global using Cookie = Microsoft.Playwright.Cookie;
global using DialogType = Microsoft.Playwright.DialogType;
global using DropPayload = Microsoft.Playwright.DropPayload;
global using ElementHandleBoundingBoxResult = Microsoft.Playwright.ElementHandleBoundingBoxResult;
global using ElementState = Microsoft.Playwright.ElementState;
global using FilePayload = Microsoft.Playwright.FilePayload;
global using ForcedColors = Microsoft.Playwright.ForcedColors;
global using Geolocation = Microsoft.Playwright.Geolocation;
global using HarContentPolicy = Microsoft.Playwright.HarContentPolicy;
global using HarMode = Microsoft.Playwright.HarMode;
global using HarNotFound = Microsoft.Playwright.HarNotFound;
global using Header = Microsoft.Playwright.Header;
global using HttpCredentials = Microsoft.Playwright.HttpCredentials;
global using HttpCredentialsSend = Microsoft.Playwright.HttpCredentialsSend;
global using IAPIRequest = Microsoft.Playwright.IAPIRequest;
global using IAPIRequestContext = Microsoft.Playwright.IAPIRequestContext;
global using IAPIResponse = Microsoft.Playwright.IAPIResponse;
global using IAPIResponseAssertions = Microsoft.Playwright.IAPIResponseAssertions;
global using IBrowser = Microsoft.Playwright.IBrowser;
global using IBrowserContext = Microsoft.Playwright.IBrowserContext;
global using IBrowserType = Microsoft.Playwright.IBrowserType;
global using ICDPSession = Microsoft.Playwright.ICDPSession;
global using ICDPSessionEvent = Microsoft.Playwright.ICDPSessionEvent;
global using IClock = Microsoft.Playwright.IClock;
global using IConsoleMessage = Microsoft.Playwright.IConsoleMessage;
global using ICredentials = Microsoft.Playwright.ICredentials;
global using IDebugger = Microsoft.Playwright.IDebugger;
global using IDialog = Microsoft.Playwright.IDialog;
global using IDownload = Microsoft.Playwright.IDownload;
global using IElementHandle = Microsoft.Playwright.IElementHandle;
global using IFileChooser = Microsoft.Playwright.IFileChooser;
global using IFormData = Microsoft.Playwright.IFormData;
global using IFrame = Microsoft.Playwright.IFrame;
global using IFrameLocator = Microsoft.Playwright.IFrameLocator;
global using IJSHandle = Microsoft.Playwright.IJSHandle;
global using IKeyboard = Microsoft.Playwright.IKeyboard;
global using ILocator = Microsoft.Playwright.ILocator;
global using ILocatorAssertions = Microsoft.Playwright.ILocatorAssertions;
global using IMouse = Microsoft.Playwright.IMouse;
global using IPage = Microsoft.Playwright.IPage;
global using IPageAssertions = Microsoft.Playwright.IPageAssertions;
global using IPlaywright = Microsoft.Playwright.IPlaywright;
global using IPlaywrightAssertions = Microsoft.Playwright.IPlaywrightAssertions;
global using IRequest = Microsoft.Playwright.IRequest;
global using IResponse = Microsoft.Playwright.IResponse;
global using IRoute = Microsoft.Playwright.IRoute;
global using IScreencast = Microsoft.Playwright.IScreencast;
global using ISelectors = Microsoft.Playwright.ISelectors;
global using ITouchscreen = Microsoft.Playwright.ITouchscreen;
global using ITracing = Microsoft.Playwright.ITracing;
global using IVideo = Microsoft.Playwright.IVideo;
global using IWebError = Microsoft.Playwright.IWebError;
global using IWebSocket = Microsoft.Playwright.IWebSocket;
global using IWebSocketFrame = Microsoft.Playwright.IWebSocketFrame;
global using IWebSocketRoute = Microsoft.Playwright.IWebSocketRoute;
global using IWebStorage = Microsoft.Playwright.IWebStorage;
global using IWorker = Microsoft.Playwright.IWorker;
global using KeyboardModifier = Microsoft.Playwright.KeyboardModifier;
global using LoadState = Microsoft.Playwright.LoadState;
global using Location = Microsoft.Playwright.Location;
global using Margin = Microsoft.Playwright.Margin;
global using Media = Microsoft.Playwright.Media;
global using MouseButton = Microsoft.Playwright.MouseButton;
global using PageViewportSizeResult = Microsoft.Playwright.PageViewportSizeResult;
global using PaperFormat = Microsoft.Playwright.PaperFormat;
global using Position = Microsoft.Playwright.Position;
global using Proxy = Microsoft.Playwright.Proxy;
global using PseudoElement = Microsoft.Playwright.PseudoElement;
global using RecordVideoSize = Microsoft.Playwright.RecordVideoSize;
global using ReducedMotion = Microsoft.Playwright.ReducedMotion;
global using RequestAbortErrorCode = Microsoft.Playwright.RequestAbortErrorCode;
global using RequestSizesResult = Microsoft.Playwright.RequestSizesResult;
global using RequestTimingResult = Microsoft.Playwright.RequestTimingResult;
global using ResponseSecurityDetailsResult = Microsoft.Playwright.ResponseSecurityDetailsResult;
global using ResponseServerAddrResult = Microsoft.Playwright.ResponseServerAddrResult;
global using RouteFromHarUpdateContentPolicy = Microsoft.Playwright.RouteFromHarUpdateContentPolicy;
global using SameSiteAttribute = Microsoft.Playwright.SameSiteAttribute;
global using ScreencastCursor = Microsoft.Playwright.ScreencastCursor;
global using ScreencastFrame = Microsoft.Playwright.ScreencastFrame;
global using ScreencastSize = Microsoft.Playwright.ScreencastSize;
global using ScreenshotAnimations = Microsoft.Playwright.ScreenshotAnimations;
global using ScreenshotCaret = Microsoft.Playwright.ScreenshotCaret;
global using ScreenshotScale = Microsoft.Playwright.ScreenshotScale;
global using ScreenshotType = Microsoft.Playwright.ScreenshotType;
global using ScreenSize = Microsoft.Playwright.ScreenSize;

// ScreenshotScale enum: Microsoft.Playwright.ScreenshotScale (Css/Device).
global using ScrollMode = Microsoft.Playwright.ScrollMode;
global using SelectOptionValue = Microsoft.Playwright.SelectOptionValue;
global using ServiceWorkerPolicy = Microsoft.Playwright.ServiceWorkerPolicy;
global using SourcePosition = Microsoft.Playwright.SourcePosition;
global using TargetPosition = Microsoft.Playwright.TargetPosition;
global using TracingStopOptions = Microsoft.Playwright.TracingStopOptions;
global using ViewportSize = Microsoft.Playwright.ViewportSize;
global using VirtualCredential = Microsoft.Playwright.VirtualCredential;
global using WaitForSelectorState = Microsoft.Playwright.WaitForSelectorState;
global using WaitUntilState = Microsoft.Playwright.WaitUntilState;
global using WebErrorLocation = Microsoft.Playwright.WebErrorLocation;
global using WebStorageItem = Microsoft.Playwright.WebStorageItem;
