/*
 * Copyright (c) Microsoft Corporation. *
 *
 * ------------------------------------------------------------------------------
 * <auto-generated>
 * This code was generated by a tool at:
 * /utils/doclint/generateDotnetApi.js
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace PlaywrightNative
{
	public enum BrowserChannel
	{
		Undefined = 0,
		[EnumMember(Value = "chrome")]
		Chrome,
		[EnumMember(Value = "chrome-beta")]
		ChromeBeta,
		[EnumMember(Value = "chrome-dev")]
		ChromeDev,
		[EnumMember(Value = "chrome-canary")]
		ChromeCanary,
		[EnumMember(Value = "msedge")]
		Msedge,
		[EnumMember(Value = "msedge-beta")]
		MsedgeBeta,
		[EnumMember(Value = "msedge-dev")]
		MsedgeDev,
		[EnumMember(Value = "msedge-canary")]
		MsedgeCanary,
	}
}
