<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>true</IsTestProject>
        <ReleaseVersion>0.0.0</ReleaseVersion>
        <NoWarn>1701;1702;NUnit2021;NUnit2026</NoWarn>
        <AssemblyName>PlaywrightNative.Tests</AssemblyName>
        <RootNamespace>PlaywrightNative.Tests</RootNamespace>
    </PropertyGroup>
    <Import Project="../Common/SignAssembly.props" />
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="NUnit" Version="4.1.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.3.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
        <PackageReference Include="CompareNETObjects" Version="4.83.0" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\PlaywrightNative.NUnit\PlaywrightNative.NUnit.csproj" />
        <ProjectReference Include="..\PlaywrightNative\PlaywrightNative.csproj" />
        <ProjectReference Include="..\PlaywrightNative.TestServer\PlaywrightNative.TestServer.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" Link="Assets\%(RecursiveDir)%(Filename)%(Extension)" />
        <None Include="Screenshots\**\*" CopyToOutputDirectory="PreserveNewest" Link="Screenshots\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
